version: '3.4'

services:
  device-registry:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000/tcp"
      - "9999:9999/udp"
      - "9999:9999/tcp"
    environment:
      - REST_API_ADDRESS=192.168.8.241
      - WEBSITE_CONTROLLER_ADDRESS=192.168.8.241
      - CONTROLLER_API_SERVER_ADDRESS=192.168.8.241
      - REST_API_PORT=3000
      - CONTROLLER_API_PORT=3001
      - WEBSITE_PORT=3005
    #stdin_open: true
    #tty: true
    network_mode: host

